name: Push trigger

on:
  push:
    tags:
      - "*"
    branches:
      - "changeset-release/*"

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Echo ref
        run: echo ${{ github.event.ref }}
